In [112]:
#This is after first Andrew Ng lesson, (October 22, 2017)

import numpy as np

In [113]:
#Houses in Atherton

# sq feet, bedrooms, bathrooms, lot size, age
x = [[1, 6660/10000, 5/10, 3.5/10, 1.15/10, (2017-2000)/100],
     [1, 8095/10000, 6/10, 6/10, 1.03/10, (2017-2013)/100],
     [1, 1970/10000, 3/10, 2/10, 1.06/10, (2017-1951)/100],
     [1, 2800/10000, 3/10, 2.5/10, 1.01/10, (2017-1958)/100],
     [1, 4675/10000, 5/10, 4/10, 1.06/10, (2017-1988)/100],
     [1, 8700/10000, 8/10, 7/10, 2.47/10, (2017-1946)/100],
     [1, 4415/10000, 5/10, 4.5/10, 1.18/10, (2017-1961)/100],
     [1, 3224/10000, 5/10, 4/10, 1.17/10, (2017-1958)/100],
     [1, 10000/10000, 8/10, 6.5/10, 1.13/10, (2017-2010)/100]]
#x = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [0, 0, 0, 0], [0, 1, 1, 0], [1, 1, 0, 0], [0, 0, 1, 1]]
y = [.9946735, .9592908, .3682425, .4694628, .6891746, 1.0531021, .5751557, .5892001, 1.0810086]
#y = [1, 1, 1, 1, 0, 1, 1, 1]

#x = digits.images.reshape((len(digits.images), -1))/100
#y = digits.target/10
m = len(x)

In [114]:
x

[[1, 0.666, 0.5, 0.35, 0.11499999999999999, 0.17],
 [1, 0.8095, 0.6, 0.6, 0.10300000000000001, 0.04],
 [1, 0.197, 0.3, 0.2, 0.10600000000000001, 0.66],
 [1, 0.28, 0.3, 0.25, 0.101, 0.59],
 [1, 0.4675, 0.5, 0.4, 0.10600000000000001, 0.29],
 [1, 0.87, 0.8, 0.7, 0.24700000000000003, 0.71],
 [1, 0.4415, 0.5, 0.45, 0.118, 0.56],
 [1, 0.3224, 0.5, 0.4, 0.11699999999999999, 0.59],
 [1, 1.0, 0.8, 0.65, 0.11299999999999999, 0.07]]

In [115]:
y

[0.9946735,
 0.9592908,
 0.3682425,
 0.4694628,
 0.6891746,
 1.0531021,
 0.5751557,
 0.5892001,
 1.0810086]

In [102]:
#Random numbers, (-1, 1)
theta = 2*np.random.random((1, len(x[0]))) - 1
n = len(theta[0])

In [103]:
print(theta)

[[ 0.48305827  0.006622    0.69492741 -0.11662463  0.62374346  0.34512164]]


In [104]:
def h(l):
    return theta.dot(l)[0]

In [105]:
h(x[0])

0.92451478884835891

In [106]:
alpha = 0.05
last_error = 0
error = 100
index = 0
while last_error != error:
    index = index + 1
    last_error = error
    temps = np.random.random((1, len(theta[0])))*0
    for b in range(m):
        error = (h(x[b]) - y[b])
        for t in range(len(temps[0])):
            temps[0][t] += error*x[b][t]
    temps = temps*(alpha/m)
    for t in range(len(temps[0])):
        theta[0][t] -= temps[0][t]
    if index % 10000 == 0:
        nE = 0
        for p in range(m):
            nE += (h(x[p]) - y[p])
        print("Error: " + str(nE/m))

Error: -7.08413064253e-06
Error: -1.58254340441e-05
Error: -1.6735731392e-05
Error: -1.58360408258e-05
Error: -1.45995845147e-05
Error: -1.33757187381e-05
Error: -1.223897697e-05
Error: -1.11982691366e-05
Error: -1.02479675989e-05
Error: -9.38008061298e-06
Error: -8.58695072157e-06
Error: -7.86171123613e-06
Error: -7.19825484492e-06
Error: -6.59112486763e-06
Error: -6.03541561336e-06
Error: -5.52669358506e-06
Error: -5.06093626288e-06
Error: -4.63448371481e-06
Error: -4.2439993054e-06
Error: -3.88643693136e-06
Error: -3.5590130559e-06
Error: -3.25918238742e-06
Error: -2.98461642264e-06
Error: -2.73318430484e-06
Error: -2.50293562603e-06
Error: -2.2920848733e-06
Error: -2.09899732236e-06
Error: -1.92217619381e-06
Error: -1.76025094697e-06
Error: -1.61196658874e-06
Error: -1.47617390709e-06
Error: -1.35182053697e-06
Error: -1.23794278817e-06
Error: -1.13365816693e-06
Error: -1.03815853014e-06
Error: -9.50703819293e-07
Error: -8.706163214e-07
Error: -7.97275417056e-07
Error: -7.3011276976

In [10]:
for i in range(m):
    print("")
    print("Guess: " + str(h(x[i])))
    print("Actual: " + str(y[i]))


Guess: 0.9946735
Actual: 0.9946735

Guess: 0.9592908
Actual: 0.9592908

Guess: 0.368242500003
Actual: 0.3682425

Guess: 0.469462799997
Actual: 0.4694628


In [108]:
# $6,891,746
#h([1, 8700/10000, 8/10, 7/10, 2.47/10, (2017-1946)/100])*10000000

In [109]:
#array([[ 1.36966098,  0.84523262, -0.70863848, -0.92528644, -0.6994236 ,
#        -1.05475995]])
theta

array([[ 0.40017685,  0.35808401,  0.43360192, -0.52705456,  3.38752389,
        -0.65745233]])

In [110]:
h([1, 8370/10000, 4/10, 4.5/10, 1.13/10, (2017-2005)/100])

0.94005530005905413